# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FormatConverter.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QHBoxLayout,
    QLabel, QLineEdit, QListView, QMainWindow,
    QPushButton, QRadioButton, QScrollArea, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1413, 796)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ShowImageView = QGraphicsView(self.centralwidget)
        self.ShowImageView.setObjectName(u"ShowImageView")
        self.ShowImageView.setGeometry(QRect(170, 30, 1231, 731))
        self.ShowImageView.setStyleSheet(u"")
        self.SaveButton = QPushButton(self.centralwidget)
        self.SaveButton.setObjectName(u"SaveButton")
        self.SaveButton.setGeometry(QRect(10, 700, 151, 61))
        font = QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.SaveButton.setFont(font)
        self.SaveButton.setStyleSheet(u"display: flex; justify-content: center; align-item: center;border: none; background-color: lightgray; border-radius: 10px")
        self.OpenFileButton = QPushButton(self.centralwidget)
        self.OpenFileButton.setObjectName(u"OpenFileButton")
        self.OpenFileButton.setGeometry(QRect(10, 10, 151, 30))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.OpenFileButton.setFont(font1)
        self.OpenFileButton.setStyleSheet(u"background-color: lightgray;\n"
" border: none;\n"
" text-align: center;\n"
"justify-content: center;\n"
" display: flex;\n"
"font-weight: bold;\n"
"border-radius: 12px;")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 210, 150, 471))
        self.scrollArea.setStyleSheet(u"border: none;\n"
"border-radius: 12px;\n"
"background-color: #E0E4EA;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 150, 471))
        self.JPEG = QRadioButton(self.scrollAreaWidgetContents)
        self.JPEG.setObjectName(u"JPEG")
        self.JPEG.setGeometry(QRect(10, 40, 121, 16))
        font2 = QFont()
        font2.setPointSize(11)
        self.JPEG.setFont(font2)
        self.JPEG.setStyleSheet(u"border: none;")
        self.PNG = QRadioButton(self.scrollAreaWidgetContents)
        self.PNG.setObjectName(u"PNG")
        self.PNG.setGeometry(QRect(10, 60, 121, 16))
        self.PNG.setFont(font2)
        self.PNG.setStyleSheet(u"border: none;")
        self.BMP = QRadioButton(self.scrollAreaWidgetContents)
        self.BMP.setObjectName(u"BMP")
        self.BMP.setGeometry(QRect(10, 80, 121, 16))
        self.BMP.setFont(font2)
        self.BMP.setStyleSheet(u"border: none;")
        self.TIFF = QRadioButton(self.scrollAreaWidgetContents)
        self.TIFF.setObjectName(u"TIFF")
        self.TIFF.setGeometry(QRect(10, 100, 121, 16))
        self.TIFF.setFont(font2)
        self.TIFF.setStyleSheet(u"border: none;")
        self.WebP = QRadioButton(self.scrollAreaWidgetContents)
        self.WebP.setObjectName(u"WebP")
        self.WebP.setGeometry(QRect(10, 120, 121, 16))
        self.WebP.setFont(font2)
        self.WebP.setStyleSheet(u"border: none;")
        self.ICO = QRadioButton(self.scrollAreaWidgetContents)
        self.ICO.setObjectName(u"ICO")
        self.ICO.setGeometry(QRect(10, 140, 121, 16))
        self.ICO.setFont(font2)
        self.ICO.setStyleSheet(u"border: none;")
        self.PPM = QRadioButton(self.scrollAreaWidgetContents)
        self.PPM.setObjectName(u"PPM")
        self.PPM.setGeometry(QRect(10, 160, 121, 16))
        self.PPM.setFont(font2)
        self.PPM.setStyleSheet(u"border: none;")
        self.TGA = QRadioButton(self.scrollAreaWidgetContents)
        self.TGA.setObjectName(u"TGA")
        self.TGA.setGeometry(QRect(10, 180, 121, 16))
        self.TGA.setFont(font2)
        self.TGA.setStyleSheet(u"border: none;")
        self.EPS = QRadioButton(self.scrollAreaWidgetContents)
        self.EPS.setObjectName(u"EPS")
        self.EPS.setGeometry(QRect(10, 270, 121, 16))
        self.EPS.setFont(font2)
        self.EPS.setStyleSheet(u"border: none;")
        self.DDS = QRadioButton(self.scrollAreaWidgetContents)
        self.DDS.setObjectName(u"DDS")
        self.DDS.setGeometry(QRect(10, 310, 121, 16))
        self.DDS.setFont(font2)
        self.DDS.setStyleSheet(u"border: none;")
        self.PDF = QRadioButton(self.scrollAreaWidgetContents)
        self.PDF.setObjectName(u"PDF")
        self.PDF.setGeometry(QRect(10, 290, 121, 16))
        self.PDF.setFont(font2)
        self.PDF.setStyleSheet(u"border: none;")
        self.PCX = QRadioButton(self.scrollAreaWidgetContents)
        self.PCX.setObjectName(u"PCX")
        self.PCX.setGeometry(QRect(10, 330, 121, 16))
        self.PCX.setFont(font2)
        self.PCX.setStyleSheet(u"border: none;")
        self.SGI = QRadioButton(self.scrollAreaWidgetContents)
        self.SGI.setObjectName(u"SGI")
        self.SGI.setGeometry(QRect(10, 350, 121, 16))
        self.SGI.setFont(font2)
        self.SGI.setStyleSheet(u"border: none;")
        self.label_5 = QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, -1, 121, 31))
        font3 = QFont()
        font3.setPointSize(12)
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"border: none; z-index: 10;")
        self.label_6 = QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 220, 100, 40))
        self.label_6.setFont(font3)
        self.label_6.setStyleSheet(u"border: none;")
        self.label_7 = QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 400, 131, 61))
        font4 = QFont()
        font4.setFamilies([u"Segoe UI Symbol"])
        font4.setPointSize(7)
        self.label_7.setFont(font4)
        self.label_7.setWordWrap(True)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 36, 151, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 680, 150, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 50, 131, 20))
        font5 = QFont()
        font5.setFamilies([u"Segoe UI Symbol"])
        self.label.setFont(font5)
        self.listView = QListView(self.centralwidget)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(10, 70, 150, 31))
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(30, 70, 111, 31))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.FormatLabel = QLabel(self.horizontalLayoutWidget)
        self.FormatLabel.setObjectName(u"FormatLabel")
        font6 = QFont()
        font6.setPointSize(9)
        self.FormatLabel.setFont(font6)

        self.horizontalLayout.addWidget(self.FormatLabel)

        self.SizeLabel = QLabel(self.horizontalLayoutWidget)
        self.SizeLabel.setObjectName(u"SizeLabel")
        self.SizeLabel.setFont(font6)

        self.horizontalLayout.addWidget(self.SizeLabel)

        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 420, 130, 10))
        font7 = QFont()
        font7.setUnderline(False)
        self.line_3.setFont(font7)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setStyleSheet(u"")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 190, 130, 20))
        self.line_4.setAutoFillBackground(False)
        self.line_4.setStyleSheet(u"z-index: 1;")
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 100, 150, 20))
        self.line_5.setAutoFillBackground(False)
        self.line_5.setStyleSheet(u"z-index: 1;")
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.width = QLineEdit(self.centralwidget)
        self.width.setObjectName(u"width")
        self.width.setGeometry(QRect(10, 140, 60, 22))
        self.height = QLineEdit(self.centralwidget)
        self.height.setObjectName(u"height")
        self.height.setGeometry(QRect(100, 140, 60, 22))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 140, 10, 20))
        self.label_2.setFont(font5)
        self.label_2.setStyleSheet(u"text-align: center;")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 120, 131, 20))
        self.label_3.setFont(font5)
        self.SetSize = QPushButton(self.centralwidget)
        self.SetSize.setObjectName(u"SetSize")
        self.SetSize.setGeometry(QRect(10, 170, 151, 24))
        self.SetSize.setStyleSheet(u"display: flex; justify-content: center; align-item: center;border: none; background-color: lightgray; border-radius: 10px")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(70, 70, 20, 29))
        self.label_4.setFont(font2)
        self.WARNING = QLabel(self.centralwidget)
        self.WARNING.setObjectName(u"WARNING")
        self.WARNING.setGeometry(QRect(170, -1, 1221, 31))
        font8 = QFont()
        font8.setFamilies([u"Segoe UI Symbol"])
        font8.setPointSize(16)
        font8.setBold(True)
        self.WARNING.setFont(font8)
        self.WARNING.setStyleSheet(u"color: red")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.SaveButton.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.OpenFileButton.setText(QCoreApplication.translate("MainWindow", u"Open file", None))
        self.JPEG.setText(QCoreApplication.translate("MainWindow", u"JPEG", None))
        self.PNG.setText(QCoreApplication.translate("MainWindow", u"PNG", None))
        self.BMP.setText(QCoreApplication.translate("MainWindow", u"BMP", None))
        self.TIFF.setText(QCoreApplication.translate("MainWindow", u"TIFF", None))
        self.WebP.setText(QCoreApplication.translate("MainWindow", u"WebP", None))
        self.ICO.setText(QCoreApplication.translate("MainWindow", u"ICO", None))
        self.PPM.setText(QCoreApplication.translate("MainWindow", u"PPM", None))
        self.TGA.setText(QCoreApplication.translate("MainWindow", u"TGA", None))
        self.EPS.setText(QCoreApplication.translate("MainWindow", u"EPS", None))
        self.DDS.setText(QCoreApplication.translate("MainWindow", u"DDS", None))
        self.PDF.setText(QCoreApplication.translate("MainWindow", u"PDF", None))
        self.PCX.setText(QCoreApplication.translate("MainWindow", u"PCX", None))
        self.SGI.setText(QCoreApplication.translate("MainWindow", u"SGI", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Edit and Read:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Read Only:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Please note, that files converted to Read Only fromats can't be reopened by this program and reconverted back", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Picked format and size:", None))
        self.FormatLabel.setText(QCoreApplication.translate("MainWindow", u"PNG", None))
        self.SizeLabel.setText(QCoreApplication.translate("MainWindow", u"168x167", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0425", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Custom resolution:", None))
        self.SetSize.setText(QCoreApplication.translate("MainWindow", u"Set Size", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.WARNING.setText("")
    # retranslateUi

